"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 56, fontSize: 11, fontFamily: "Helvetica", lineHeight: 1.5 },
  header: { fontSize: 10, color: "#475569", marginBottom: 20, textAlign: "right" },
  body: { whiteSpace: "pre-wrap" },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 56,
    right: 56,
    fontSize: 9,
    color: "#64748b",
    textAlign: "center",
    borderTop: "1px solid #e2e8f0",
    paddingTop: 8,
  },
});

export function AppealPDF({ letter }: { letter: string }) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.header}>{date}</Text>
        <View style={styles.body}>
          <Text>{letter}</Text>
        </View>
        <Text style={styles.footer}>
          Generated by OverturnIt — drafting tool, not legal advice.
        </Text>
      </Page>
    </Document>
  );
}
